Création d'un user via l'API POST /users
ESIR-SI-2020/Commands pull request #6
Opened 2019-11-28 15:00 UTC by Theomariee

Ajout du handling de la création d'un user sur requête POST /users.
Contrôle métier sur les champs du body.
Manque connexion ElasticSearch pour vérifier que le user à ajouter n'existe pas déjà.

2019-11-29 14:29 UTC, AntoineCheron requested changes

2019-11-29 14:29 UTC, AntoineCheron commented on pom.xml
> +            <groupId>com.jxc</groupId>
outdated

2019-11-29 14:29 UTC, AntoineCheron commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Supprimer `.idea`

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/DTO/UserCreationDTO.java
> +import org.slf4j.LoggerFactory;
Imports pas propres

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/DTO/UserCreationDTO.java
> +    public Address address;
`final` sur tous pour être cohérent avec @Value

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/DTO/UserCreationDTO.java
> +    private final static Logger logger = LoggerFactory.getLogger(UserCreationDTO.class);
Annotation pour ça

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/controllers/UserController.java
> +@RestController("/users")
Pourquoi 2 sauts de ligne ?

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/controllers/UserController.java
> +    private final static Logger logger = LoggerFactory.getLogger(UserController.class);
Utiliser l'annotation

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/controllers/UserController.java
> +        UserCreationDTO.validateUserCreationRequest(newUser);
Dommage de ne pas déclarer explicitement l'exception qui pourrait être remontée

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/controllers/UserController.java
> +    @ResponseStatus(HttpStatus.CREATED)
Pas bon le code d'erreur, pour deux raisons. Pourquoi ?

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/controllers/UserController.java
> +        }
Toutes ces lignes qui vérifient des règles métier devraient être dans un service

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/services/KafkaProducer.java
> +    Logger logger = LoggerFactory.getLogger(KafkaProducer.class);
Annotation

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/services/UserWriteService.java
> +    Logger logger = LoggerFactory.getLogger(UserWriteService.class);
Annotation

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/services/UserWriteService.java
> +    public UserWriteService(@Autowired  KafkaProducer kafkaProducer) {
Pas très cohérent ton utilisation d'Autowired pour construire tes classes

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/utils/CheckEmailFormat.java
> +public class CheckEmailFormat {
```suggestion
public class EmailFormatChecker {
```

➜ c'est une classe pas une fonction, répercuter ça sur la fonction

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/utils/CheckEmailFormat.java
> +        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@" +  //part before @
Oulalalala surtout pas le mettre ici. Pourquoi ?

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/utils/CheckEmailFormat.java
> +        Pattern pat = Pattern.compile(emailRegex);
Ca non plus d'ailleurs

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/utils/CheckEmailFormat.java
> +            return false;
Pourquoi le faire ici et pas dès le début ?

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/utils/Hash.java
> +            // TODO: replace with logger
Fais le dès maintenant ;)

2019-11-29 14:29 UTC, AntoineCheron commented on src/main/java/fr/esir/jxc/utils/Hash.java
> +            return s; // should not happened
`should not happen`

2020-01-12 17:54 UTC, AntoineCheron commented
@Theomariee prend en compte mes commentaires stp

2020-01-16 07:25 UTC, Theomariee commented
Merged into develop.

2020-01-16 07:25 UTC, closed without merging